version: '3.8'

services:
  ballerina:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root  # Replace with your MySQL username
      MYSQL_PASSWORD: pass123  # Replace with your MySQL password
      MYSQL_DATABASE: MentorLinkDB  # Replace with your MySQL database name
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass123  # Change to a secure password
      MYSQL_DATABASE: MentorLinkDB  # Replace with your MySQL database name
      MYSQL_USER: root  # Replace with your MySQL username
      MYSQL_PASSWORD: pass123  # Replace with your MySQL password
    ports:
      - "3306:3306"
